my:
  mqtt:
    host: tcp://sdadgz.cn:1883
    client-id: test_server
    username: admin
    password: sdadgz.cn
    timeout: 1000
    keep-alive: 10
spring:
  redis:
    host: sdadgz.cn
    port: 6379
